# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/selenium-devtools/all/selenium-devtools.rbi
#
# selenium-devtools-0.103.0

module Selenium
end
module Selenium::DevTools
  def self.load_version; end
  def self.version; end
  def self.version=(arg0); end
end
