# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/websocket/all/websocket.rbi
#
# websocket-1.2.9

module WebSocket
  def self.max_frame_size; end
  def self.max_frame_size=(val); end
  def self.should_raise; end
  def self.should_raise=(val); end
end
