// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

// import { application } from "./application"

// import HelloController from "./hello_controller"
// application.register("hello", HelloController)
import { create, cssomSheet } from 'twind'

// This creates a twind "sheet" which is a wrapper
// around a CSS stylesheet
const sheet = cssomSheet({ target: new CSSStyleSheet() });

// This gets an instance of the tw helper for our
// stylesheet above. Meaning any time we use `tw`, it will
// append the right CSS to our custom stylesheet.
const { tw } = create({ sheet });

import { html, LitElement } from 'lit';

export class MyElement extends LitElement {
    static styles = [sheet.target];
    createRenderRoot() {
        return this; // turn off shadow dom to access external styles
    }
    render() {
        return html`
            <label for="my-modal" class=${tw`btn modal-button`}>open modal</label>

            <!-- Put this part before </body> tag -->
            <input type="checkbox" id="my-modal" class="modal-toggle" />
            <div class="modal">
            <div class="modal-box">
                <h3 class="font-bold text-lg">Congratulations random Interner user!</h3>
                <p class="py-4">You've been selected for a chance to get one year of subscription to use Wikipedia for free!</p>
                <div class="modal-action">
                <label for="my-modal" class="btn">Yay!</label>
                </div>
            </div>
            </div>
    `;
    }
}

window.customElements.define('my-element', MyElement);